# Generated by Django 2.0.4 on 2018-04-20 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='記事名')),
                ('published', models.DateTimeField(verbose_name='投稿日')),
                ('image', models.ImageField(upload_to='media/', verbose_name='画像')),
                ('body', models.TextField(verbose_name='本文')),
            ],
        ),
    ]
