# Generated by Django 2.0.4 on 2018-05-06 02:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='記事名')),
                ('body', models.TextField(verbose_name='内容')),
                ('thumbnail', models.ImageField(blank=True, upload_to='media/', verbose_name='サムネイル')),
                ('conditions', models.IntegerField(verbose_name='公開非公開設定')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_admin_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='投稿日時')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_admin_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='コミュニティ名')),
                ('description', models.TextField(verbose_name='コミュニティの説明')),
                ('is_public', models.BooleanField(default=True, verbose_name='公開非公開設定')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('articles', models.ManyToManyField(to='curation.Article', verbose_name='記事')),
                ('permitted_user', models.ManyToManyField(related_name='permitted_user', to=settings.AUTH_USER_MODEL, verbose_name='許可されたユーザー')),
                ('stand_by_user', models.ManyToManyField(related_name='stand_by_user', to=settings.AUTH_USER_MODEL, verbose_name='承認待ちのユーザー')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='comment',
            field=models.ManyToManyField(to='curation.Comment', verbose_name='コメント'),
        ),
        migrations.AddField(
            model_name='article',
            name='like_user',
            field=models.ManyToManyField(related_name='article_like_user', to=settings.AUTH_USER_MODEL, verbose_name='いいねしたユーザー'),
        ),
    ]
