# Generated by Django 2.0.4 on 2018-05-06 02:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curation_comment_admin_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
