# Generated by Django 2.0.4 on 2018-05-06 19:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curation', '0002_auto_20180506_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='comment',
            field=models.ManyToManyField(blank=True, to='curation.Comment', verbose_name='コメント'),
        ),
        migrations.AlterField(
            model_name='community',
            name='articles',
            field=models.ManyToManyField(blank=True, to='curation.Article', verbose_name='記事'),
        ),
        migrations.AlterField(
            model_name='community',
            name='permitted_user',
            field=models.ManyToManyField(blank=True, related_name='permitted_user', to=settings.AUTH_USER_MODEL, verbose_name='許可されたユーザー'),
        ),
        migrations.AlterField(
            model_name='community',
            name='stand_by_user',
            field=models.ManyToManyField(blank=True, related_name='stand_by_user', to=settings.AUTH_USER_MODEL, verbose_name='承認待ちのユーザー'),
        ),
    ]
