# Generated by Django 2.0.4 on 2018-05-06 21:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curation', '0003_auto_20180507_0446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='like_user',
            field=models.ManyToManyField(blank=True, related_name='article_like_user', to=settings.AUTH_USER_MODEL, verbose_name='いいねしたユーザー'),
        ),
    ]
