# Generated by Django 2.0.4 on 2018-05-09 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curation', '0004_auto_20180507_0609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='conditions',
            field=models.BooleanField(default=True, verbose_name='公開非公開設定'),
        ),
    ]
