# Generated by Django 2.0.4 on 2018-05-09 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curation', '0005_auto_20180509_1304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='conditions',
            new_name='is_public',
        ),
    ]
