# Generated by Django 2.0.4 on 2018-05-09 07:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('curation', '0006_auto_20180509_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='articles',
        ),
        migrations.AddField(
            model_name='article',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curation.Community', blank=True, null=True),
            preserve_default=False,
        ),
    ]
