# Generated by Django 2.0.4 on 2018-05-09 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curation', '0007_auto_20180509_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='community',
            field=models.ForeignKey(default=int, on_delete=django.db.models.deletion.CASCADE, to='curation.Community'),
        ),
    ]
