# Generated by Django 2.0.4 on 2018-05-05 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20180505_1310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='created_ad',
            new_name='created_at',
        ),
    ]
