# Generated by Django 2.0.4 on 2018-05-06 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20180505_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='変更日時'),
        ),
    ]
